python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 0 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 1 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 2 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 3 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 4 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 5 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 6 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 7 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 8 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 9 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 10 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 11 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 12 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 13 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 14 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 15 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 16 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 17 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 18 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 19 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 20 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 21 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 22 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 23 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 24 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 25 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 26 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 27 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 28 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 29 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 30 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 31 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 32 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 33 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 34 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 35 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 36 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 37 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 38 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 39 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 40 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 41 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 42 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 43 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 44 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 45 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 46 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 47 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 48 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 49 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 50 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 51 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 52 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 53 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 54 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 55 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 56 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 57 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 58 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 59 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 60 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 61 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 62 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset train --seg-duration 16 --groups 64 --job-index 63 &


python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 0 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 1 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 2 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 3 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 4 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 5 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 6 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 7 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 8 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 9 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 10 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 11 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 12 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 13 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 14 &
python preprocess_lrs2lrs3.py --data-dir /home/agent_h/data/datasets/lrs3/ --landmarks-dir /home/agent_h/data/datasets/LRS3_landmarks/ --detector retinaface --root-dir /home/agent_h/data/datasets/autoavsr_lrs3 --dataset lrs3 --gpu_type cuda --subset test --seg-duration 16 --groups 16 --job-index 15 &


python merge.py \
    --root-dir /home/agent_h/data/datasets/autoavsr_lrs3/ \
    --dataset lrs3 \
    --subset train \
    --seg-duration 16 \
    --groups 64 
    
python merge.py \
    --root-dir /home/agent_h/data/datasets/autoavsr_lrs3/ \
    --dataset lrs3 \
    --subset test \
    --seg-duration 16 \
    --groups 16
    
python train.py --exp-dir="/home/agent_h/data/ckpts/" \
                --exp-name="0201_0119_autoavsr_lrs3v0" \
                --modality="video" \
                --root-dir="/home/agent_h/data/datasets/autoavsr_lrs3/" \
                --train-file="/home/agent_h/data/datasets/autoavsr_lrs3/labels/lrs3_train_transcript_lengths_seg16s.csv" \
                --val-file="/home/agent_h/data/datasets/autoavsr_lrs3/labels/lrs3_test_transcript_lengths_seg16s.csv" \
                --test-file="/home/agent_h/data/datasets/autoavsr_lrs3/labels/lrs3_test_transcript_lengths_seg16s.csv" \
                --num-nodes=1
                
python train.py --exp-dir="/home/agent_h/data/ckpts/" \
                --exp-name="0201_0119_autoavsr_lrs3v1" \
                --modality="video" \
                --root-dir="/home/agent_h/data/datasets/autoavsr_lrs3/" \
                --train-file="/home/agent_h/data/datasets/autoavsr_lrs3/labels/lrs3_train_transcript_lengths_seg16s.csv" \
                --val-file="/home/agent_h/data/datasets/autoavsr_lrs3/labels/lrs3_test_transcript_lengths_seg16s.csv" \
                --test-file="/home/agent_h/data/datasets/autoavsr_lrs3/labels/lrs3_test_transcript_lengths_seg16s.csv" \
                --num-nodes=1