_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
ckpt_path:
    value: null
ctc_weight:
    value: 0.1
debug:
    value: false
exp_dir:
    value: /home/agent_h/data/ckpts/
exp_name:
    value: 0201_0119_autoavsr_lrs3v0
gpus:
    value: 8
group_name:
    value: null
lr:
    value: 0.001
max_epochs:
    value: 75
max_frames:
    value: 1600
modality:
    value: video
num_nodes:
    value: 1
pretrained_model_path:
    value: null
root_dir:
    value: /home/agent_h/data/datasets/autoavsr_lrs3_train/
slurm_job_id:
    value: 0
test_file:
    value: /home/agent_h/data/datasets/autoavsr_lrs3_train/labels/lrs3_train_transcript_lengths_seg16s.csv
train_file:
    value: /home/agent_h/data/datasets/autoavsr_lrs3_train/labels/lrs3_train_transcript_lengths_seg16s.csv
train_num_buckets:
    value: 400
transfer_encoder:
    value: false
transfer_frontend:
    value: false
val_file:
    value: /home/agent_h/data/datasets/autoavsr_lrs3_train/labels/lrs3_train_transcript_lengths_seg16s.csv
warmup_epochs:
    value: 5
weight_decay:
    value: 0.03
