_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
